"<!DOCTYPE html>"
"<html>"
"<head>"
"<title>WiFi Configration</title>"
"<style type=\"text/css\">"
"h1 { font-size: 150%; }"
"body .container {width: 300px; margin: 0 auto; padding: 1em;}"
".networks {width: 15em; list-style: none; margin: 1em 0; padding: 0;}"
".networks li {cursor: pointer; text-decoration: underline; padding: 0.25em;}"
".networks li.secure::after {content: \" *\";}"
".networks li.selected {font-weight: bold;}"
".networks li:hover {background-color: #eee;}"
"form div {margin-bottom: 1em; padding: 0.25em;}"
"</style>"
"</head>"
"<body>"
"    <div class=\"container\">"
"        <h1>Join WiFi network</h1>"
"        <form action=\"/settings\" method=\"get\">"
"            <input type=\"submit\" value=\"Refresh\" />"
"        </form>"
"        <form action=\"/settings\" method=\"post\">",

"            <ul class=\"networks\">",

"                <li class=\"%ssecure\">%s</li>",

"            </ul>",

"            <input type=\"text\" id=\"ssid\" name=\"ssid\" style=\"display: none;\" />"
""
"            <div class=\"password\" style=\"display: none;\">"
"                <label for=\"password\">Password</label>"
"                <input type=\"password\" id=\"password\" name=\"password\" />"
"            </div>"
""
"            <input type=\"submit\" id=\"join\" value=\"Join\" disabled />"
"        </form>"
"    </div>"
"    <script>"
"var ssid_field, password_block, password_field, join_button;"
""
"ssid_field = document.getElementById('ssid');"
"password_block = document.querySelector('form div.password');"
"password_field = document.getElementById('password');"
"join_button = document.getElementById('join');"
""
"function enable(e) { e.disabled = ''; }"
"function disable(e) { e.disabled = 'disabled'; }"
"function show(e) { e.style.display = 'block'; }"
"function hide(e) { e.style.display = 'none'; }"
""
"function selectNetwork(e) {"
"    let nets = document.querySelectorAll('ul.networks li');"
"    for (var i=0; i<nets.length; i++) {"
"        nets[i].classList.remove('selected');"
"    }"
"    e.classList.add('selected');"
"}"
""
"var nets, i;"
"nets = document.querySelectorAll('ul.networks li.unsecure');"
"for (i=0; i<nets.length; i++) {"
"    nets[i].onclick = function(event) {"
"        event.preventDefault();"
"        selectNetwork(this);"
"        ssid_field.value = this.innerHTML;"
"        hide(password_block);"
"        disable(password_field);"
"        password_field.value = '';"
"        enable(join_button);"
"    }"
"}"
""
"nets = document.querySelectorAll('ul.networks li.secure');"
"for (i=0; i<nets.length; i++) {"
"    nets[i].onclick = function(event) {"
"        event.preventDefault();"
"        selectNetwork(this);"
"        ssid_field.value = this.innerHTML;"
"        enable(password_field);"
"        show(password_block);"
"        disable(join_button);"
"    }"
"}"
""
"let p = password_field;"
"p.onchange = p.onkeydown = p.onpaste = p.oninput = function(event) {"
"    ((this.value == '') ? disable : enable)(join_button);"
"}"
"    </script>"
"</body>"
"</html>"
